apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
    version: v1
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app
    spec:
      
      serviceAccountName: sa-nodeapp

      containers:
      - name: node-app
        image: developer9844/express:4.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      
        env:
        - name: DB_HOST
          value: "mysql.mysql.svc.cluster.local"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_NAME
          value: "test_db"

        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  labels:
    version: v1
    app: node-app
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: node-app
  
