apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-role
  namespace: mysql
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-rolebinding
  namespace: mysql
subjects:
- kind: ServiceAccount
  name: sa-nodeapp
  namespace: default
roleRef:
  kind: Role
  name: mysql-role
  apiGroup: rbac.authorization.k8s.io
